INSERT INTO Tipe_Kamar (nama_tipe, deskripsi, kapasitas, harga_per_malam, fasilitas)
VALUES
('Single', 'Kamar dengan satu tempat tidur single, cocok untuk satu orang.', 1, 500000.00, 'WiFi, TV, AC, Kamar mandi, Meja kerja'),
('Double', 'Kamar dengan tempat tidur double, cocok untuk dua orang.', 2, 750000.00, 'WiFi, TV, AC, Kamar mandi pribadi, Meja kerja'),
('Suite', 'Kamar luas dengan fasilitas mewah, cocok untuk keluarga kecil.', 4, 1500000.00, 'WiFi, TV, AC, Mini Bar, Dapur kecil, Sofa, Kamar mandi besar'),
('Executive', 'Kamar dengan fasilitas eksekutif untuk perjalanan bisnis.', 2, 2000000.00, 'WiFi, TV, AC, Mini Bar, Sofa, Balkon, Ruang kerja, Kamar mandi dengan bathtub'),
('Family', 'Kamar luas dengan tempat tidur tambahan untuk keluarga.', 5, 1400000.00, 'WiFi, TV, AC, Area bermain anak, Balkon, Kamar mandi pribadi, Ruang keluarga'),
('Studio', 'Kamar dengang gaya studio dilengkapi dapur kecil untuk kebutuhan sehari-hari.', 2, 800000.00, 'WiFi, TV, AC, Dapur kecil, Kamar mandi pribadi'),
('Deluxe', 'Kamar deluxe dengan fasilitas premium dan pemandangan kota.', 2, 1000000.00, 'WiFi, TV, AC, Mini Bar, Dapur, Ruang kerja, Kamar mandi besar, Balkon pribadi'),
('Superior', 'Kamar dengan pemandangan luar biasa dan fasilitas mewah.', 3, 1250000.00, 'WiFi, TV, AC, Balkon pribadi, Mini Bar, Kamar mandi besar'),
('Junior Suite', 'Suite kecil dengan ruang tamu dan fasilitas tambahan.', 3, 1600000.00, 'WiFi, TV, AC, Mini Bar, Ruang tamu, Kamar mandi dengan bathtub'),
('Presidential', 'Suite paling mewah dengan fasilitas istimewa dan kolam renang pribadi.', 5, 5000000.00, 'WiFi, TV, AC, Mini Bar, Kolam renang pribadi, Jacuzzi, Ruang makan, Ruang tamu'),
('Cabana', 'Kamar dengan fasilitas ala pantai dan pemandangan laut langsung.', 2, 2200000.00, 'WiFi, TV, AC, Pemandangan laut, Teras pribadi, Kamar mandi besar'),
('Penthouse', 'Penthouse eksklusif dengan pemandangan kota dan fasilitas terbaik.', 4, 4500000.00, 'WiFi, TV, AC, Mini Bar, Teras pribadi, Kamar mandi dengan bathtub, Jacuzzi, Balkon'),
('Honeymoon Suite', 'Suite romantis untuk pasangan pengantin dengan fasilitas mewah.', 2, 3000000.00, 'WiFi, TV, AC, Mini Bar, Jacuzzi, Kamar mandi besar, Balkon'),
('Business', 'Kamar khusus untuk bisnis dengan ruang kerja dan fasilitas tambahan.', 2, 2000000.00, 'WiFi, TV, AC, Ruang kerja, Kamar mandi pribadi, Meja kerja'),
('Dormitory', 'Kamar dengan tempat tidur susun untuk backpacker dan wisatawan hemat.', 8, 300000.00, 'WiFi, AC, Kamar mandi bersama'),
('Cabin', 'Kamar berbentuk kabin dengan pemandangan alam dan suasana rustic.', 3, 800000.00, 'WiFi, TV, AC, Perapian, Pemandangan alam, Kamar mandi pribadi'),
('Luxury Tent', 'Tenda mewah dengan semua fasilitas modern untuk pengalaman unik.', 2, 1800000.00, 'WiFi, TV, AC, Mini Bar, Pemandangan alam, Kamar mandi pribadi'),
('Family Suite', 'Suite keluarga dengan ruang ekstra dan fasilitas nyaman.', 6, 1300000.00, 'WiFi, TV, AC, Area bermain anak, Kamar mandi besar, Ruang keluarga'),
('King Room', 'Kamar dengan tempat tidur king-size dan fasilitas premium.', 2, 1200000.00, 'WiFi, TV, AC, Meja kerja, Kamar mandi pribadi'),
('Queen Room', 'Kamar dengan tempat tidur queen-size dan fasilitas lengkap.', 2, 1000000.00, 'WiFi, TV, AC, Kamar mandi pribadi, Meja kerja'),
('Shared Room', 'Kamar bersama dengan tempat tidur susun dan fasilitas hemat.', 4, 400000.00, 'WiFi, AC, Kamar mandi bersama'),
('Sky View', 'Kamar dengan pemandangan langit kota yang menakjubkan.', 2, 2000000.00, 'WiFi, TV, AC, Balkon pribadi, Mini Bar'),
('Garden Suite', 'Suite dengan pemandangan taman yang indah dan suasana tenang.', 3, 1800000.00, 'WiFi, TV, AC, Balkon pribadi, Pemandangan taman, Mini Bar'),
('Spa Suite', 'Suite dengan akses ke spa pribadi untuk relaksasi maksimal.', 2, 2500000.00, 'WiFi, TV, AC, Spa pribadi, Jacuzzi, Kamar mandi mewah'),
('Eco Room', 'Kamar ramah lingkungan dengan fasilitas hemat energi dan bahan alami.', 2, 900000.00, 'WiFi, TV, AC, Bahan ramah lingkungan, Kamar mandi'),
('Antique Room', 'Kamar dengan dekorasi antik dan suasana nostalgia.', 2, 1700000.00, 'WiFi, TV, AC, Perabot antik, Kamar mandi klasik'),
('Loft', 'Kamar bergaya loft dengan ruang terbuka dan desain modern.', 2, 1100000.00, 'WiFi, TV, AC, Dapur kecil, Kamar mandi pribadi'),
('Luxury Room', 'Kamar mewah dengan furnitur dan dekorasi premium.', 2, 3000000.00, 'WiFi, TV, AC, Mini Bar, Ruang tamu, Kamar mandi besar'),
('Compact Room', 'Kamar kecil dengan fasilitas dasar namun nyaman.', 1, 600000.00, 'WiFi, TV, AC, Kamar mandi pribadi'),
('Zen Suite', 'Suite dengan suasana tenang untuk meditasi dan relaksasi.', 2, 2200000.00, 'WiFi, TV, AC, Area meditasi, Balkon pribadi');